import * as workerpool from "workerpool";
// @ts-expect-error tsc doesn't understand special web worker base64 urls generated by vite
import WorkerURL from "./worker?url&worker";

export function createWorkerpool() {
  return workerpool.pool(WorkerURL, {
    workerOpts: {
      type: import.meta.env.PROD ? undefined : "module",
    },
  });
}
